# 基础镜像
FROM redis
# author
MAINTAINER fish

# 挂载目录
VOLUME /home/lokhub/redis
# 创建目录
RUN mkdir -p /home/lokhub/redis
# 指定路径
WORKDIR /home/lokhub/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/lokhub/redis/redis.conf
