# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER fish

# 挂载目录
VOLUME /home/lokhub
# 创建目录
RUN mkdir -p /home/lokhub
# 指定路径
WORKDIR /home/lokhub
# 复制jar文件到路径
COPY ./jar/lokhub-gateway.jar /home/lokhub/lokhub-gateway.jar

# 启动网关服务
ENTRYPOINT ["java","-jar","lokhub-gateway.jar"]